name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  apk:
    name: Build Release signed APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
  
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
  
      - name: Build Release APK
        run: ./gradlew assembleRelease
  
      - name: Sign APK
        run: ./gradlew assembleRelease
  
      - name: Upload Signed APK
        uses: actions/upload-artifact@v2
        with:
          name: sample-app-signed  # Artifact Name
          path: app/build/outputs/apk/release/*.apk 
  
  deploy:
    name: Deploy release AAB on Playstore
    needs: [apk]
    runs-on: ubuntu-latest
    steps:
      - name: Create service_account.json
        uses: actions/checkout@v2
  
      - name: Deploy to Play Store
        uses: actions/checkout@v2
