name: Build and Release APK

on:
  push:
    branches: [mster]
  pull_request:
    branches: [main]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Build APK
        run: ./gradlew assembleRelease